# Generated by Django 4.0.3 on 2022-03-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_dance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceskill',
            name='style',
        ),
    ]
