# Generated by Django 4.0.3 on 2022-03-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_danceskill_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceskill',
            name='dance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='club.dance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='danceskill',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='club.dancer'),
        ),
    ]
