# Generated by Django 4.0.3 on 2022-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_danceskill_dance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dance',
            name='style',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
