# Generated by Django 4.0.3 on 2022-03-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_danceskill_dance_alter_danceskill_dancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceskill',
            name='dance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='club.dance'),
        ),
    ]
